# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyqt5-tools\qt5_applications\Qt\bin\API_Viewer_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import logging
import sys

from src import access_api_functions

from src.field_format_funcs import (ble_msg_fields_dict, ble_device_name,
                                    ble_device_addr, ble_msg_str, ble_gatt_read_uuid, ble_gatt_write_uuid,
                                    ble_msg_result_str_dict, ble_msg_result_str)


# We declare a custom MyDialog class so we can overload a few selected methods from the default QtWidgets.QDialog class
class MyDialog(QtWidgets.QDialog):
    def __init__(self):
        # We call the constructor of the base class (QDialog) so we can initialise and modify base class attributes
        super().__init__()

    # When we close the main GUI Dialog Box, we also want to close all other Application Processes
    def closeEvent(self, event):
        logging.info("Close Event Function was called")
        sys.exit()


# This thread corresponds to the Flask Server that is configured in (access_api_functions.py)
class FlaskThread(QtCore.QThread):
    def __init__(self, parent=None):
        QtCore.QThread.__init__(self, parent)

        # The cancel button will update this value to True to stop the Flask server.
        self.exiting = False

        # We need to start the Application API server in parallel to the GUI
        self.flask_server = access_api_functions.api

    def run(self):
        logging.info("Starting Flask Server at http://127.0.0.1:5900 ....")
        self.flask_server.run(host=access_api_functions.server_ip, port=access_api_functions.server_port)


class Ui_API_Viewer_Dialog(object):

    def __init__(self):
        # Start the Flask Server Thread
        self.flask_thread = FlaskThread()
        self.flask_server_start()

        # We use a QTimer to synchronise the values (updated through the API) every second
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_field_values)
        self.timer.start(1000)

    def flask_server_start(self):
        self.flask_thread.setPriority(QtCore.QThread.Priority.HighPriority)
        self.flask_thread.start()

    # Function gets called every second to be updated with the values of the "global" ble_msg_fields_dict dictionary
    # This dictionary is updated through the API functions defined in (access_api_functions.py)
    def update_field_values(self):
        self.BLE_Device_Name_Dynamic_Label.setText(ble_msg_fields_dict[ble_device_name])
        self.BLE_Device_Addr_Dynamic_Label.setText(ble_msg_fields_dict[ble_device_addr])
        self.BLE_Gatt_Write_Dynamic_Label.setText(ble_msg_fields_dict[ble_gatt_write_uuid])
        self.BLE_Gatt_Read_Dynamic_Label.setText(ble_msg_fields_dict[ble_gatt_read_uuid])
        self.Message_Dynamic_Label.setText(ble_msg_fields_dict[ble_msg_str])
        self.Reply_Dynamic_Label.setText(ble_msg_result_str_dict[ble_msg_result_str])

    def setupUi(self, API_Viewer_Dialog):

        API_Viewer_Dialog.setObjectName("API_Viewer_Dialog")
        # We manually need to enable the "minimize" button for the dialog box
        API_Viewer_Dialog.setWindowFlags(API_Viewer_Dialog.windowFlags() | QtCore.Qt.WindowMinimizeButtonHint)
        # We manually assign a fixed size for the main GUI Dialog Box
        API_Viewer_Dialog.setFixedSize(390, 675)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(API_Viewer_Dialog.sizePolicy().hasHeightForWidth())
        API_Viewer_Dialog.setSizePolicy(sizePolicy)

        self.Fixed_Explanation_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.Fixed_Explanation_Label.setGeometry(QtCore.QRect(30, 20, 331, 21))
        self.Fixed_Explanation_Label.setStyleSheet("font: 75 9pt \"Arial\";")
        self.Fixed_Explanation_Label.setObjectName("Fixed_Explanation_Label")

        self.BLE_Device_Name_Static_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.BLE_Device_Name_Static_Label.setGeometry(QtCore.QRect(30, 60, 241, 21))
        self.BLE_Device_Name_Static_Label.setStyleSheet("font: 75 10pt \"Arial\";")
        self.BLE_Device_Name_Static_Label.setObjectName("BLE_Device_Name_Static_Label")
        self.BLE_Device_Name_Dynamic_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.BLE_Device_Name_Dynamic_Label.setGeometry(QtCore.QRect(30, 80, 331, 41))
        self.BLE_Device_Name_Dynamic_Label.setStyleSheet("background-color: rgb(255, 255, 255);\n""font: 8pt \"Arial\";")
        self.BLE_Device_Name_Dynamic_Label.setWordWrap(True)
        self.BLE_Device_Name_Dynamic_Label.setObjectName("BLE_Device_Name_Dynamic_Label")
        self.BLE_Device_Name_Explanation_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.BLE_Device_Name_Explanation_Label.setGeometry(QtCore.QRect(30, 120, 311, 21))
        self.BLE_Device_Name_Explanation_Label.setStyleSheet("font: 75 8pt \"Arial\";")
        self.BLE_Device_Name_Explanation_Label.setObjectName("BLE_Device_Name_Explanation_Label")


        self.BLE_Device_Addr_Static_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.BLE_Device_Addr_Static_Label.setGeometry(QtCore.QRect(30, 150, 241, 21))
        self.BLE_Device_Addr_Static_Label.setStyleSheet("font: 75 10pt \"Arial\";")
        self.BLE_Device_Addr_Static_Label.setObjectName("BLE_Device_Addr_Static_Label")
        self.BLE_Device_Addr_Dynamic_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.BLE_Device_Addr_Dynamic_Label.setGeometry(QtCore.QRect(30, 170, 331, 21))
        self.BLE_Device_Addr_Dynamic_Label.setStyleSheet("background-color: rgb(255, 255, 255);\n""font: 8pt \"Arial\";")
        self.BLE_Device_Addr_Dynamic_Label.setWordWrap(True)
        self.BLE_Device_Addr_Dynamic_Label.setObjectName("BLE_Device_Addr_Dynamic_Label")
        self.BLE_Device_Addr_Explanation_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.BLE_Device_Addr_Explanation_Label.setGeometry(QtCore.QRect(30, 190, 341, 21))
        self.BLE_Device_Addr_Explanation_Label.setStyleSheet("font: 75 8pt \"Arial\";")
        self.BLE_Device_Addr_Explanation_Label.setObjectName("BLE_Device_Addr_Explanation_Label")


        self.BLE_Gatt_Write_Explanation_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.BLE_Gatt_Write_Explanation_Label.setGeometry(QtCore.QRect(30, 280, 311, 21))
        self.BLE_Gatt_Write_Explanation_Label.setStyleSheet("font: 75 8pt \"Arial\";")
        self.BLE_Gatt_Write_Explanation_Label.setObjectName("BLE_Gatt_Write_Explanation_Label")
        self.BLE_Gatt_Write_Dynamic_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.BLE_Gatt_Write_Dynamic_Label.setGeometry(QtCore.QRect(30, 240, 331, 41))
        self.BLE_Gatt_Write_Dynamic_Label.setStyleSheet("background-color: rgb(255, 255, 255);\n""font: 8pt \"Arial\";")
        self.BLE_Gatt_Write_Dynamic_Label.setWordWrap(True)
        self.BLE_Gatt_Write_Dynamic_Label.setObjectName("BLE_Gatt_Write_Dynamic_Label")
        self.BLE_Gatt_Write_Static_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.BLE_Gatt_Write_Static_Label.setGeometry(QtCore.QRect(30, 220, 241, 21))
        self.BLE_Gatt_Write_Static_Label.setStyleSheet("font: 75 10pt \"Arial\";")
        self.BLE_Gatt_Write_Static_Label.setObjectName("BLE_Gatt_Write_Static_Label")


        self.BLE_Gatt_Read_Dynamic_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.BLE_Gatt_Read_Dynamic_Label.setGeometry(QtCore.QRect(30, 330, 331, 41))
        self.BLE_Gatt_Read_Dynamic_Label.setStyleSheet("background-color: rgb(255, 255, 255);\n""font: 8pt \"Arial\";")
        self.BLE_Gatt_Read_Dynamic_Label.setWordWrap(True)
        self.BLE_Gatt_Read_Dynamic_Label.setObjectName("BLE_Gatt_Read_Dynamic_Label")
        self.BLE_Gatt_Read_Explanation_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.BLE_Gatt_Read_Explanation_Label.setGeometry(QtCore.QRect(30, 370, 311, 21))
        self.BLE_Gatt_Read_Explanation_Label.setStyleSheet("font: 75 8pt \"Arial\";")
        self.BLE_Gatt_Read_Explanation_Label.setObjectName("BLE_Gatt_Read_Explanation_Label")
        self.BLE_Gatt_Read_Static_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.BLE_Gatt_Read_Static_Label.setGeometry(QtCore.QRect(30, 310, 241, 21))
        self.BLE_Gatt_Read_Static_Label.setStyleSheet("font: 75 10pt \"Arial\";")
        self.BLE_Gatt_Read_Static_Label.setObjectName("BLE_Gatt_Read_Static_Label")


        self.Message_Static_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.Message_Static_Label.setGeometry(QtCore.QRect(30, 400, 241, 21))
        self.Message_Static_Label.setStyleSheet("font: 75 10pt \"Arial\";")
        self.Message_Static_Label.setObjectName("Message_Static_Label")
        self.Message_Explanation_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.Message_Explanation_Label.setGeometry(QtCore.QRect(30, 500, 311, 21))
        self.Message_Explanation_Label.setStyleSheet("font: 75 8pt \"Arial\";")
        self.Message_Explanation_Label.setObjectName("Message_Explanation_Label")

        self.scrollArea = QtWidgets.QScrollArea(API_Viewer_Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(30, 420, 331, 81))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.msg_scrollAreaContents = QtWidgets.QWidget()
        self.msg_scrollAreaContents.setGeometry(QtCore.QRect(0, 0, 312, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msg_scrollAreaContents.sizePolicy().hasHeightForWidth())
        self.msg_scrollAreaContents.setSizePolicy(sizePolicy)
        # The Height value of the scrollAreaContents can be increased if needed (also requires Dynamic_Label height to increase)
        self.msg_scrollAreaContents.setMinimumSize(QtCore.QSize(0, 1500))
        self.msg_scrollAreaContents.setObjectName("msg_scrollAreaContents")
        self.Message_Dynamic_Label = QtWidgets.QLabel(self.msg_scrollAreaContents)
        self.Message_Dynamic_Label.setGeometry(QtCore.QRect(0, 0, 312, 1500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Message_Dynamic_Label.sizePolicy().hasHeightForWidth())
        self.Message_Dynamic_Label.setSizePolicy(sizePolicy)
        self.Message_Dynamic_Label.setMinimumSize(QtCore.QSize(0, 600))
        self.Message_Dynamic_Label.setStyleSheet("font: 8pt \"Arial\";\n""background-color: rgb(255, 255, 255);")
        self.Message_Dynamic_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Message_Dynamic_Label.setWordWrap(True)
        self.Message_Dynamic_Label.setObjectName("Message_Dynamic_Label")
        self.scrollArea.setWidget(self.msg_scrollAreaContents)


        self.Reply_Explanation_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.Reply_Explanation_Label.setGeometry(QtCore.QRect(30, 640, 311, 21))
        self.Reply_Explanation_Label.setStyleSheet("font: 75 8pt \"Arial\";")
        self.Reply_Explanation_Label.setObjectName("Reply_Explanation_Label")
        self.Reply_Static_Label = QtWidgets.QLabel(API_Viewer_Dialog)
        self.Reply_Static_Label.setGeometry(QtCore.QRect(30, 530, 261, 21))
        self.Reply_Static_Label.setStyleSheet("font: 75 10pt \"Arial\";")
        self.Reply_Static_Label.setObjectName("Reply_Static_Label")

        self.scrollArea_2 = QtWidgets.QScrollArea(API_Viewer_Dialog)
        self.scrollArea_2.setGeometry(QtCore.QRect(30, 560, 331, 81))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.reply_scrollAreaContents = QtWidgets.QWidget()
        self.reply_scrollAreaContents.setGeometry(QtCore.QRect(0, 0, 312, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reply_scrollAreaContents.sizePolicy().hasHeightForWidth())
        self.reply_scrollAreaContents.setSizePolicy(sizePolicy)
        # The Height value of the scrollAreaContents can be increased if needed (also requires Dynamic_Label height to increase)
        self.reply_scrollAreaContents.setMinimumSize(QtCore.QSize(0, 1500))
        self.reply_scrollAreaContents.setObjectName("reply_scrollAreaContents")
        self.Reply_Dynamic_Label = QtWidgets.QLabel(self.reply_scrollAreaContents)
        self.Reply_Dynamic_Label.setGeometry(QtCore.QRect(0, 0, 312, 1500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reply_Dynamic_Label.sizePolicy().hasHeightForWidth())
        self.Reply_Dynamic_Label.setSizePolicy(sizePolicy)
        self.Reply_Dynamic_Label.setMinimumSize(QtCore.QSize(0, 600))
        self.Reply_Dynamic_Label.setStyleSheet("font: 8pt \"Arial\";\n""background-color: rgb(255, 255, 255);")
        self.Reply_Dynamic_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Reply_Dynamic_Label.setWordWrap(True)
        self.Reply_Dynamic_Label.setObjectName("Reply_Dynamic_Label")
        self.scrollArea_2.setWidget(self.reply_scrollAreaContents)

        self.retranslateUi(API_Viewer_Dialog)
        QtCore.QMetaObject.connectSlotsByName(API_Viewer_Dialog)

    def retranslateUi(self, API_Viewer_Dialog):
        _translate = QtCore.QCoreApplication.translate
        API_Viewer_Dialog.setWindowTitle(_translate("API_Viewer_Dialog", "Dialog"))
        self.BLE_Device_Name_Static_Label.setText(_translate("API_Viewer_Dialog", "BLE Device Name (Most Recent)"))
        self.Fixed_Explanation_Label.setText(_translate("API_Viewer_Dialog", "Updated values are shown here based on API function calls"))
        self.BLE_Device_Addr_Static_Label.setText(_translate("API_Viewer_Dialog", "BLE Device Address (Most Recent)"))
        self.BLE_Device_Name_Explanation_Label.setText(_translate("API_Viewer_Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Accessed by:</span> PUT http://127.0.0.1:5900/device/name/&lt;name&gt;</p></body></html>"))
        self.BLE_Device_Addr_Explanation_Label.setText(_translate("API_Viewer_Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Accessed by</span>: PUT http://127.0.0.1:5900/device/address/&lt;address&gt;</p></body></html>"))
        self.BLE_Gatt_Write_Explanation_Label.setText(_translate("API_Viewer_Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Accessed by:</span> PUT http://127.0.0.1:5900/gatt/write/&lt;uuid&gt;</p></body></html>"))
        self.BLE_Gatt_Write_Static_Label.setText(_translate("API_Viewer_Dialog", "BLE GATT Write UUID (Most Recent)"))
        self.BLE_Gatt_Read_Explanation_Label.setText(_translate("API_Viewer_Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Accessed by:</span> PUT http://127.0.0.1:5900/gatt/read/&lt;uuid&gt;</p></body></html>"))
        self.BLE_Gatt_Read_Static_Label.setText(_translate("API_Viewer_Dialog", "BLE GATT Read UUID (Most Recent)"))
        self.Message_Static_Label.setText(_translate("API_Viewer_Dialog", "Message to Send (Most Recent)"))
        self.Message_Explanation_Label.setText(_translate("API_Viewer_Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Accessed by:</span> PUT http://127.0.0.1:5900/msg/&lt;message&gt;</p></body></html>"))
        self.Reply_Explanation_Label.setText(_translate("API_Viewer_Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Accessed by:</span> GET http://127.0.0.1:5900/result_str</p></body></html>"))
        self.Reply_Static_Label.setText(_translate("API_Viewer_Dialog", "Reply from BLE GATT Server (Most Recent)"))


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    # Removes the annoying "?" button which is hard to access in the Python programming
    app.setAttribute(QtCore.Qt.ApplicationAttribute.AA_DisableWindowContextHelpButton)

    API_Viewer_Dialog = MyDialog()
    ui = Ui_API_Viewer_Dialog()
    ui.setupUi(API_Viewer_Dialog)
    API_Viewer_Dialog.show()
    sys.exit(app.exec_())
