# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyqt5-tools\qt5_applications\Qt\bin\Help_Init_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Help_Dialog(object):
    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        # We manually need to enable the "minimize" button for the dialog box
        Dialog.setWindowFlags(Dialog.windowFlags() | QtCore.Qt.WindowMinimizeButtonHint)
        Dialog.setFixedSize(400, 540)

        self.Intro_Title_Label = QtWidgets.QLabel(Dialog)
        self.Intro_Title_Label.setGeometry(QtCore.QRect(30, 10, 91, 21))
        self.Intro_Title_Label.setStyleSheet("font: 75 11pt \"Arial\";")
        self.Intro_Title_Label.setObjectName("Intro_Title_Label")
        self.Intro_Text_Label = QtWidgets.QLabel(Dialog)
        self.Intro_Text_Label.setGeometry(QtCore.QRect(30, 30, 351, 51))
        self.Intro_Text_Label.setStyleSheet("font: 75 8pt \"Arial\";")
        self.Intro_Text_Label.setWordWrap(True)
        self.Intro_Text_Label.setObjectName("Intro_Text_Label")

        self.Note1_Text_Label = QtWidgets.QLabel(Dialog)
        self.Note1_Text_Label.setGeometry(QtCore.QRect(30, 80, 341, 51))
        self.Note1_Text_Label.setStyleSheet("font: 75 8pt \"Arial\";")
        self.Note1_Text_Label.setWordWrap(True)
        self.Note1_Text_Label.setObjectName("Note1_Text_Label")

        self.Note2_Text_Label = QtWidgets.QLabel(Dialog)
        self.Note2_Text_Label.setGeometry(QtCore.QRect(30, 130, 341, 41))
        self.Note2_Text_Label.setStyleSheet("font: 75 8pt \"Arial\";")
        self.Note2_Text_Label.setWordWrap(True)
        self.Note2_Text_Label.setObjectName("Note2_Text_Label")

        self.UsingApp_Title_Label = QtWidgets.QLabel(Dialog)
        self.UsingApp_Title_Label.setGeometry(QtCore.QRect(30, 180, 111, 21))
        self.UsingApp_Title_Label.setStyleSheet("font: 75 11pt \"Arial\";")
        self.UsingApp_Title_Label.setObjectName("UsingApp_Title_Label")
        self.UsingApp_Text_Label = QtWidgets.QLabel(Dialog)
        self.UsingApp_Text_Label.setGeometry(QtCore.QRect(30, 190, 351, 51))
        self.UsingApp_Text_Label.setStyleSheet("font: 75 8pt \"Arial\";")
        self.UsingApp_Text_Label.setWordWrap(True)
        self.UsingApp_Text_Label.setObjectName("UsingApp_Text_Label")

        self.DeviceName_Text_Label = QtWidgets.QLabel(Dialog)
        self.DeviceName_Text_Label.setGeometry(QtCore.QRect(30, 230, 351, 51))
        self.DeviceName_Text_Label.setStyleSheet("font: 75 8pt \"Arial\";")
        self.DeviceName_Text_Label.setWordWrap(True)
        self.DeviceName_Text_Label.setObjectName("DeviceName_Text_Label")

        self.DeviceAddr_Text_Label = QtWidgets.QLabel(Dialog)
        self.DeviceAddr_Text_Label.setGeometry(QtCore.QRect(30, 280, 351, 61))
        self.DeviceAddr_Text_Label.setStyleSheet("font: 75 8pt \"Arial\";")
        self.DeviceAddr_Text_Label.setWordWrap(True)
        self.DeviceAddr_Text_Label.setObjectName("DeviceAddr_Text_Label")

        self.GattWrite_Text_Label = QtWidgets.QLabel(Dialog)
        self.GattWrite_Text_Label.setGeometry(QtCore.QRect(30, 350, 351, 51))
        self.GattWrite_Text_Label.setStyleSheet("font: 75 8pt \"Arial\";")
        self.GattWrite_Text_Label.setWordWrap(True)
        self.GattWrite_Text_Label.setObjectName("GattWrite_Text_Label")

        self.GattRead_Text_Label = QtWidgets.QLabel(Dialog)
        self.GattRead_Text_Label.setGeometry(QtCore.QRect(30, 410, 351, 51))
        self.GattRead_Text_Label.setStyleSheet("font: 75 8pt \"Arial\";")
        self.GattRead_Text_Label.setWordWrap(True)
        self.GattRead_Text_Label.setObjectName("GattRead_Text_Label")

        self.Message_Text_Label = QtWidgets.QLabel(Dialog)
        self.Message_Text_Label.setGeometry(QtCore.QRect(30, 470, 351, 51))
        self.Message_Text_Label.setStyleSheet("font: 75 8pt \"Arial\";")
        self.Message_Text_Label.setWordWrap(True)
        self.Message_Text_Label.setObjectName("GattRead_Text_Label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Intro_Title_Label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Introduction</span></p></body></html>"))
        self.Intro_Text_Label.setText(_translate("Dialog", "<html><head/><body><p align=\"justify\">This application was developed as a tool for interacting with BLE devices using GATT characteristics for inbound/outbound messaging (and GAP device discovery).</p></body></html>"))
        self.Note1_Text_Label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Note</span>: This application was only tested for the Windows 10 Bluetooth stack (compatibility is not guaranteed for later versions of the OS).</p></body></html>"))
        self.Note2_Text_Label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Note</span>: This application is a self-container Executable (.EXE) file, which does not require any additional dependencies.</p></body></html>"))
        self.UsingApp_Title_Label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Using this App</span></p></body></html>"))
        self.UsingApp_Text_Label.setText(_translate("Dialog", "<html><head/><body><p align=\"justify\">To use this app to successfully communicate with a BLE device, you need to know the following values:</p></body></html>"))
        self.DeviceName_Text_Label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">BLE Device Name</span>: Some BLE devices will be configured to advertise their services using Generic Access Profile (GAP) under a certain name.</p></body></html>"))
        self.DeviceAddr_Text_Label.setText(_translate("Dialog", "<html><head/><body><p align=\"justify\"><span style=\" font-weight:600;\">BLE Device MAC Address</span>: BLE devices that advertise their services using GAP all have MAC address that can be used for connection. It is recommended not to supply both the MAC address and the Device Name, simply enter either one.</p></body></html>"))
        self.GattWrite_Text_Label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">BLE Device GATT Write Characteristic UUID</span>: Without delving into detail on GATT, the Write characteristic  UUID is required so that this app can message the BLE device.</p></body></html>"))
        self.GattRead_Text_Label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">BLE Device GATT Read Characteristic UUID</span>: Without delving into detail on GATT, the Read characteristic UUID is required so that this app can receive replies from the BLE device.</p></body></html>"))
        self.Message_Text_Label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Message</span>: The plain string message to be sent over to the BLE device. This app cannot change the data type of the message being sent (UTF-8 encoded string).</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # Removes the annoying "?" button which is hard to access in the Python programming
    app.setAttribute(QtCore.Qt.ApplicationAttribute.AA_DisableWindowContextHelpButton)

    Dialog = QtWidgets.QDialog()
    ui = Ui_Help_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
